openapi: 3.0.0
info:
  title: Tagify
  version: '1.0'
  description: ''
  contact:
    name: Karol Rogoza
  license:
    name: GNU General Public License v3.0
    url: 'https://fsf.org'
servers:
  - url: 'http://localhost:5000'
paths:
  /api/auth/me:
    get:
      summary: whoami
      tags:
        - Auth
        - user
      responses:
        '200':
          description: OK
        '401':
          description: 'Unauthorized, you need to be logged in'
      operationId: get-api-auth
      description: 'get user information (user & admin)'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
            examples:
              example:
                value:
                  username: user1
    parameters: []
  /api/auth/login:
    post:
      summary: login
      tags:
        - Auth
      responses:
        '200':
          description: OK
        '401':
          description: 'Unauthorized, wrong password or user_name'
      operationId: post-api-auth-login
      description: 'login (user & admin)'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            examples:
              example:
                value:
                  username: user1
                  password: password
        description: user data needed for authentication
  /api/auth/logout:
    post:
      summary: logout
      tags:
        - Auth
      responses:
        '200':
          description: OK
      operationId: post-api-auth-logout
      description: 'logout (user & admin)'
      parameters: []
      requestBody:
        content:
          application/xml:
            schema:
              type: object
              properties:
                username:
                  type: string
            examples:
              example:
                value:
                  username: user1
        description: ''
components:
  schemas: {}
  securitySchemes: {}
